import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, Clock3, Eye, RefreshCw, TicketCheck, Users } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { supabase } from '../lib/supabase';

type Visit={id:string;started_at:string;ended_at:string|null;session_duration_seconds:number;device_type:string;avg_fps:number;completed_quest:boolean};
type Event={event_type:string;timestamp:string;brand_key:string|null;exhibit_id:string|null};
const dayKey=(v:string)=>new Date(v).toISOString().slice(0,10);
const duration=(seconds:number)=>seconds<60?`${Math.round(seconds)}s`:`${Math.floor(seconds/60)}m ${Math.round(seconds%60)}s`;

export default function DashboardPage(){
 const [days,setDays]=useState(30); const [visits,setVisits]=useState<Visit[]>([]); const [events,setEvents]=useState<Event[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [updated,setUpdated]=useState<Date|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');const since=new Date(Date.now()-days*864e5).toISOString();const [v,e]=await Promise.all([supabase.from('visitor_sessions').select('id,started_at,ended_at,session_duration_seconds,device_type,avg_fps,completed_quest').gte('started_at',since).order('started_at'),supabase.from('telemetry_events').select('event_type,timestamp,brand_key,exhibit_id').gte('timestamp',since).order('timestamp')]);if(v.error||e.error)setError(v.error?.message||e.error?.message||'Analytics could not be loaded.');else{setVisits((v.data||[]) as Visit[]);setEvents((e.data||[]) as Event[]);setUpdated(new Date())}setLoading(false)},[days]);
 useEffect(()=>{void load()},[load]);
 const analytics=useMemo(()=>{const ended=visits.filter(v=>v.ended_at||v.session_duration_seconds>0);const avg=ended.length?ended.reduce((a,v)=>a+Number(v.session_duration_seconds||0),0)/ended.length:0;const active=visits.filter(v=>!v.ended_at&&Date.now()-new Date(v.started_at).getTime()<15*60e3).length;const inspect=events.filter(e=>e.event_type==='exhibit_inspect_opened').length;const coupons=events.filter(e=>e.event_type==='coupon_code_copied').length;const outbound=events.filter(e=>e.event_type==='brand_outbound_clicked').length;const dates=Array.from({length:days},(_,i)=>{const d=new Date(Date.now()-(days-1-i)*864e5).toISOString().slice(0,10);return {date:d,label:new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'}),sessions:visits.filter(v=>dayKey(v.started_at)===d).length,inspections:events.filter(e=>e.event_type==='exhibit_inspect_opened'&&dayKey(e.timestamp)===d).length}});const devices=Object.entries(visits.reduce<Record<string,number>>((a,v)=>{a[v.device_type||'unknown']=(a[v.device_type||'unknown']||0)+1;return a},{})).map(([name,value])=>({name,value}));return {avg,active,inspect,coupons,outbound,dates,devices}},[visits,events,days]);
 const cards=[[Users,'Sessions',visits.length,'Visits started in period'],[Activity,'Active now',analytics.active,'Seen in the last 15 minutes'],[Clock3,'Average visit',duration(analytics.avg),'Completed or measured visits'],[Eye,'Artwork inspections',analytics.inspect,'Inspect panel opened'],[TicketCheck,'Rewards copied',analytics.coupons,`${analytics.outbound} partner site visits`]] as const;
 return <div><header className="page-header"><div><p className="eyebrow">Operations intelligence</p><h1>Museum overview</h1><p className="muted">Live, privacy-conscious visitor and engagement analytics.</p></div><div className="header-actions"><select className="admin-input compact" value={days} onChange={e=>setDays(Number(e.target.value))} aria-label="Date range"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select><button className="admin-button admin-button-secondary" onClick={()=>void load()} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>Refresh</button></div></header>
 {error&&<div className="notice error">Unable to load live analytics. {error}</div>}
 <div className="status-row"><span><span className="live-dot"/>Live Supabase data</span><span>{updated?`Updated ${updated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'Connecting…'}</span></div>
 <section className="metric-grid">{cards.map(([Icon,label,value,note])=><article className="metric-card" key={label}><div className="metric-icon"><Icon size={19}/></div><div><span>{label}</span><strong>{loading?'—':value}</strong><small>{note}</small></div></article>)}</section>
 <section className="analytics-grid"><article className="admin-card chart-wide"><div className="card-heading"><div><h2>Visitor activity</h2><p>Sessions and exhibit inspections over time</p></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={analytics.dates}><defs><linearGradient id="traffic" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#78a9ff" stopOpacity={.3}/><stop offset="95%" stopColor="#78a9ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#252b35" vertical={false}/><XAxis dataKey="label" tick={{fill:'#87919f',fontSize:11}} tickLine={false} axisLine={false} minTickGap={24}/><YAxis allowDecimals={false} tick={{fill:'#87919f',fontSize:11}} tickLine={false} axisLine={false}/><Tooltip contentStyle={{background:'#15191f',border:'1px solid #303744',borderRadius:10}}/><Area type="monotone" dataKey="sessions" stroke="#78a9ff" strokeWidth={2} fill="url(#traffic)"/><Area type="monotone" dataKey="inspections" stroke="#b7f36b" fill="transparent"/></AreaChart></ResponsiveContainer></div></article>
 <article className="admin-card"><div className="card-heading"><div><h2>Device mix</h2><p>How visitors enter the museum</p></div></div>{analytics.devices.length?<div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.devices} layout="vertical"><XAxis type="number" allowDecimals={false} hide/><YAxis dataKey="name" type="category" width={70} tick={{fill:'#aab2bd',fontSize:12}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#15191f',border:'1px solid #303744',borderRadius:10}}/><Bar dataKey="value" fill="#b7f36b" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div>:<Empty/>}</article></section>
 {!loading&&!visits.length&&!events.length&&<div className="empty-panel"><Activity/><h2>No activity in this period</h2><p>Real visitor sessions will appear here as people enter the museum. No sample data is used.</p></div>}
 </div>;
}
function Empty(){return <div className="empty-small">No device data yet</div>}
