import React, { useEffect } from 'react';
import './LegalPage.css';

type LegalPageProps = { type: 'privacy' | 'terms' };
const SITE_URL = 'https://at30.io';
const WHATSAPP_URL = 'https://wa.me/14094229714?text=Hello%20AT30%2C%20I%20have%20a%20question%20about%20your%20website.';

const setMeta = (name: string, content: string) => {
  let element = document.querySelector<HTMLMetaElement>(`meta[name="${name}"]`);
  if (!element) { element = document.createElement('meta'); element.name = name; document.head.appendChild(element); }
  element.content = content;
};

export const LegalPage: React.FC<LegalPageProps> = ({ type }) => {
  const isPrivacy = type === 'privacy';
  const title = isPrivacy ? 'Privacy Policy | AT30' : 'Terms of Use | AT30';
  const description = isPrivacy ? 'How AT30 handles information across its multiplayer events, games, and experiences.' : 'The rules for using AT30 events, games, and multiplayer experiences.';
  useEffect(() => {
    document.title = title; setMeta('description', description);
    document.querySelector<HTMLLinkElement>('link[rel="canonical"]')?.setAttribute('href', `${SITE_URL}/${type}`);
  }, [description, title, type]);
  return <main className="legal-shell">
    <nav className="legal-nav" aria-label="Legal page navigation"><a className="legal-brand" href="/" aria-label="Return to AT30 home"><span>AT30</span><small>Multiplayer experiences</small></a><a className="legal-home" href="/">Back to AT30</a></nav>
    <article className="legal-document"><header><p className="legal-kicker">AT30 / LEGAL</p><h1>{isPrivacy ? 'Privacy policy' : 'Terms of use'}</h1><p className="legal-effective">Effective 23 August 2026 · Last updated 23 August 2026</p><p className="legal-summary">{description}</p></header>{isPrivacy ? <PrivacyPolicy /> : <TermsOfUse />}</article>
    <footer className="legal-footer"><span>© 2026 AT30</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">Contact</a></div></footer>
  </main>;
};

const PrivacyPolicy = () => <div className="legal-sections">
  <section><h2>1. Who this policy covers</h2><p>This policy applies to the AT30 platform, including its seasonal events, games, company-hosted worlds, multiplayer features, website pages, and the AT30 Digital Museum MVP. “AT30,” “we,” and “us” refer to the platform operator. A hosted company experience or external partner website may also provide its own privacy notice.</p></section>
  <section><h2>2. Information we collect</h2><div><p>We collect the information needed to operate, secure, and improve the museum:</p><ul><li><strong>Visitor choices:</strong> the display name and avatar colour you choose, reward progress, exhibits inspected, and whether you complete the quest.</li><li><strong>Session and device data:</strong> an anonymous account and session identifier, visit times and duration, browser and operating-system details, device and input type, screen resolution, graphics renderer, and average frame rate.</li><li><strong>Interaction analytics:</strong> rooms entered, exhibit and guide interactions, reward and partner-link actions, and error or performance events.</li><li><strong>Position samples:</strong> your in-museum x/z coordinates and current room, sampled approximately every five seconds while you play. We do not collect GPS or real-world precise location through this feature.</li><li><strong>Multiplayer presence:</strong> your display name, avatar colour, avatar movement, and short speech-bubble messages sent to nearby players. Speech bubbles are transmitted live and are not intentionally saved as chat history by the current experience.</li><li><strong>Information you send us:</strong> messages and account details you provide when contacting AT30 through WhatsApp or another channel.</li></ul></div></section>
  <section><h2>3. How we use information</h2><p>We use information to run AT30 events, games, and multiplayer experiences; remember relevant preferences and progress; show nearby players; measure gameplay, exhibit, event, and campaign engagement; diagnose performance; protect the platform from misuse; and respond to enquiries. We do not currently sell personal information or use AT30 telemetry for cross-context behavioural advertising.</p></section>
  <section><h2>4. Where information is stored</h2><p>Your browser stores your display name, avatar colour, reward progress, and a session identifier using local or session storage. Operational records are processed through Supabase, our database, authentication, and real-time infrastructure provider. Artwork and font assets may be requested from external content providers, which may receive standard network information such as your IP address and browser headers.</p></section>
  <section><h2>5. Sharing and external links</h2><p>We share information with service providers only as needed to host, secure, analyse, and operate AT30. If you follow a partner link or contact us on WhatsApp, the destination provider receives information under its own policy. We may also disclose information when required by law, to protect users or the service, or as part of a business transaction subject to appropriate safeguards.</p></section>
  <section><h2>6. Retention</h2><p>Browser-stored preferences remain until you clear site data. Operational analytics are retained only for as long as reasonably needed for platform operations, security, performance analysis, event or partner reporting, and legal obligations, then deleted or aggregated. Live multiplayer presence ends when you disconnect.</p></section>
  <section><h2>7. Your choices and rights</h2><p>You can use a nickname, change your avatar, avoid sending speech bubbles, leave the museum, clear this site’s browser storage, or choose not to open partner links. Depending on where you live, you may have rights to access, correct, delete, restrict, or object to certain processing, or receive a copy of information associated with you. Because visits are anonymous, we may need your session details to locate a record and may be unable to connect a record to you.</p></section>
  <section><h2>8. Children</h2><p>AT30 is not directed to children under 13, and they should not use the experience or submit personal information. If you believe a child has provided information, contact us so we can investigate and remove it where appropriate.</p></section>
  <section><h2>9. Security and international processing</h2><p>We use reasonable technical and organisational safeguards, but no online service can guarantee absolute security. AT30 and its providers may process information in countries other than your own, where privacy laws may differ. Where required, appropriate transfer safeguards should apply.</p></section>
  <section><h2>10. Changes and contact</h2><p>We may update this policy as the platform adds new events, games, hosting formats, and features. We will revise the date above and provide additional notice when a change is material. For a privacy request or question, <a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">message AT30 on WhatsApp at +1 409 422 9714</a>. Please do not send passwords or sensitive information.</p></section>
</div>;

const TermsOfUse = () => <div className="legal-sections">
  <section><h2>1. Agreement</h2><p>These terms govern your access to the AT30 platform and its events, games, and multiplayer experiences, including AT30 Digital Museum. By entering or using AT30, you agree to them. If you do not agree, do not use the service. You must be at least 13 years old; if you are under the age of majority where you live, a parent or guardian must approve your use.</p></section>
  <section><h2>2. The platform and its experiences</h2><p>AT30 provides browser-based seasonal events, games, company-hosted worlds, multiplayer presence, speech bubbles, quests, partner placements, and promotional rewards. Each experience may include additional event rules, eligibility requirements, or notices. Features, content, schedules, availability, and supported devices may change. We may suspend or discontinue any part of the platform.</p></section>
  <section><h2>3. Visitor conduct</h2><p>You may use AT30 for lawful, personal exploration. You must not harass or impersonate others; send hateful, sexual, threatening, deceptive, or unlawful messages; expose personal information; disrupt multiplayer sessions; probe or bypass security; automate access without permission; reverse engineer protected portions of the service; or use AT30 to infringe anyone’s rights. We may limit or end access when reasonably necessary to protect visitors or the service.</p></section>
  <section><h2>4. Display names and player messages</h2><p>Choose a suitable display name and keep speech bubbles respectful. Messages may be visible to nearby players. Do not include phone numbers, addresses, passwords, financial information, or other sensitive data. You are responsible for content you submit and grant AT30 the limited right to transmit and display it as needed to provide the feature.</p></section>
  <section><h2>5. Intellectual property</h2><p>AT30’s software, environments, design, branding, and original content are owned by AT30 or its licensors and are protected by applicable intellectual-property laws. Artwork, trademarks, and partner content remain the property of their respective owners. These terms give you a limited, revocable, non-transferable right to use the experience; they do not transfer ownership.</p></section>
  <section><h2>6. Promotions and external services</h2><p>Rewards, coupon codes, and partner offers may have separate eligibility rules, expiry dates, availability limits, or redemption requirements. Partners—not AT30—are responsible for their products, fulfilment, and external websites unless expressly stated otherwise. Review the destination’s terms and privacy policy before proceeding.</p></section>
  <section><h2>7. Availability and disclaimers</h2><p>The service is provided “as is” and “as available.” To the extent permitted by law, AT30 disclaims implied warranties, including merchantability, fitness for a particular purpose, non-infringement, and uninterrupted or error-free operation. Nothing in these terms excludes rights or warranties that cannot legally be excluded.</p></section>
  <section><h2>8. Limitation of liability</h2><p>To the extent permitted by law, AT30 will not be liable for indirect, incidental, special, consequential, or punitive loss, or for lost data, profits, opportunities, or goodwill arising from use of the service. AT30’s total liability for claims relating to the free experience will not exceed US $100. These limitations do not apply where prohibited or to liability that cannot legally be limited.</p></section>
  <section><h2>9. Changes, disputes, and general terms</h2><p>We may update these terms and will change the effective date when we do. Continued use after an update means you accept the revised terms. Before bringing a formal claim, please contact us and allow a reasonable opportunity to resolve it. Applicable law and courts will be determined by mandatory law and AT30’s place of establishment; mandatory consumer protections in your home jurisdiction remain unaffected. If one provision is unenforceable, the others remain effective.</p></section>
  <section><h2>10. Contact</h2><p>Questions about these terms, permissions, advertising, or partnerships can be sent by <a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">WhatsApp to +1 409 422 9714</a>.</p></section>
</div>;
